---
title: "R Notebook"
output: html_notebook
---

```{r, echo=FALSE, include=FALSE}
library(tidyverse)
library(lubridate)
library(R.utils)
library(scales)
```
```{r Data: Vaccinations, echo=FALSE, include=FALSE}
data <- read.csv("data/covid19za_timeline_vaccination.csv")
head(data)
```


```{r tidying, echo=FALSE, include=FALSE}
vaccinations <- data %>%
  mutate(date = dmy(date)) %>%
  mutate(daily=vaccinations-lag(vaccinations,default=0)) %>% # calculate daily vaccinations
  mutate(total = vaccinations) %>%
  select(date, daily, total)

head(vaccinations)
```

```{r Plot daily vaccinations, echo=FALSE}
ggplot(vaccinations, aes(date, daily)) + 
  geom_col() +
  scale_x_date(breaks = NULL) +
  scale_y_continuous(breaks=c(0, 50000, 100000), labels = comma, minor_breaks = NULL) +
  labs(title= "Daily Vaccinations",
       caption = "Updated: June 2021",
       x = NULL,
       y = NULL) +
  theme_minimal() +
  theme(plot.caption = element_text(hjust = 0))

```
```{r Plot total vaccinations, echo=FALSE}
ggplot(vaccinations, aes(date, total)) + 
  geom_line(color = "blue") +
  #scale_y_continuous(breaks = seq(0, 2500000, by = 500000), limits = c(0, 2500000), labels = comma, minor_breaks = NULL) +
  scale_y_continuous(labels = comma, minor_breaks = NULL) +
  scale_x_date(breaks = NULL) + 
  geom_text(aes(label = total), data = tail(vaccinations, 1), nudge_y = 100000) +
  labs(title= "Total Vaccinations",
       caption = "Updated: June 2021",
       x = NULL,
       y = NULL) +
  theme_minimal() +
  theme(plot.caption = element_text(hjust = 0))
```

