---
title: "R Notebook"
output: html_notebook
---

```{r Setup, echo=FALSE, include=FALSE}
library(tidyverse)
library(lubridate)
```

```{r Data: Confirmed Cases, echo=FALSE, include=FALSE}
data <- read.csv("data/covid19za_provincial_cumulative_timeline_confirmed.csv")
head(data)
```
```{r Tidy data, echo=FALSE, include=FALSE}
cases <- data %>% 
  pivot_longer(c('EC', 'FS', 'GP', 'KZN', 'LP', 'MP', 'NC', 'NW', 'WC', 'UNKNOWN'), 
               names_to = "province", values_to = "cases")
cases <- cases %>% 
  select(date, province, cases, total)  %>% 
  filter(province != 'UNKNOWN')
cases <- cases %>% mutate(date = dmy(date))

head(cases)
```


```{r Plot, echo=FALSE, include=FALSE}
ggplot(cases, aes(date, cases)) + 
  geom_smooth(color = "blue") + 
  scale_y_continuous(breaks = seq(0, 1000000, by = 100000), limits = c(0, 1000000), labels = NULL) +
  scale_x_date(labels = NULL) +
  facet_wrap(~ province, nrow = 2) +
  theme_minimal() +
  labs(title= "Confirmed Cases by Province",
       x = NULL,
       y = NULL)

```
```{r, echo=FALSE}
library(RcppRoll)

cases <- cases %>%
  group_by(province) %>%
  mutate(daily_cases=cases-lag(cases,default=0)) %>%
  mutate(rolling_avg = roll_mean(daily_cases, n=7, fill = NA, align = "right"))

cases_last_8_mths <- cases %>%
  filter(date >= ymd("2020-11-12"))


```
```{r, echo=FALSE}
ggplot(cases_last_8_mths, aes(date, rolling_avg)) + 
  geom_line(color = "blue") + 
  scale_y_continuous(labels = NULL, breaks = NULL) +
  scale_x_date(breaks = NULL) +
  facet_wrap(~ province, nrow = 2) +
  labs(title= "Daily Case Trends per Province",
       x = NULL,
       y = NULL)
```

```{r, echo=FALSE, include=FALSE}
province_population <- read.csv("data/province_population.csv")
province_population

total_cases <- tail(cases, 9) # cumulative cases per province up to 21 June 2021
total_cases <- total_cases %>%
  ungroup() %>%
  mutate(code = province) %>%
  select(code, cases) %>%
  left_join(province_population, by = "code") %>% # add province populations to province cases
  select(code, province, cases, population) %>%
  mutate(cases_per_100k = round(100000 * cases / population, digits=2)) %>% # calculate infections per 100k population
  arrange(cases_per_100k)

total_cases$province <- factor(total_cases$province, levels = total_cases$province) # keep order when plotting
  
total_cases
```
```{r plot deaths by province per 100k, echo=FALSE}
ggplot(total_cases, aes(province, cases_per_100k)) + 
  geom_col() +
  geom_text(aes(label = format(cases_per_100k, big.mark=",")), hjust = 0) +
  scale_x_discrete() +
  scale_y_continuous(labels = NULL) +
  labs(title= "Prov Infections per 100,000 Population",
       caption = "Updated: June 2021",
       x = NULL,
       y = NULL) +
  coord_flip() +
  theme_minimal() +
  theme(plot.caption = element_text(hjust = 0),
        panel.grid = element_blank())
```

