---
title: "Get data from media sources"
output: html_notebook
---

```{r}
library(rtweet)
library(tidyverse)
```

```{r}
app_name<-"covid_news_tweets"
consumer_key<-"bpvgj1v8U2DVuGkydfUVbn7Fd"
consumer_secret<-"rLi8BEDEMhY2b94XunH1Trmw8EvWXsH62uD9J4W8BpjLFaVaxc"
access_token<-"1406939447346798597-MGGIwaG9ZIMrNRMh2I8UjhN6R5UHRt"
access_token_secret<-"OJoAcrwf00quax6lXYQpvd84ffArkceymB0cB16vu2yjl"
```

```{r}
create_token(app=app_name,
             consumer_key = consumer_key,
             consumer_secret = consumer_secret,
             access_token = access_token,
             access_secret = access_token_secret)
```
```{r}
# number of tweets to collect
n_tweets = 3200
```

```{r}
# how to find tweets from their IDs
lookup_tweets(c("1349557374877577218", "1403067237670526976"))
```

# Government ZA
```{r}
govZA_tweets_full <- get_timeline("governmentZA", n=n_tweets)
```
```{r}
# take out columns consisting of NA values
govZA_tweets <- govZA_tweets_full[, colSums(!is.na(govZA_tweets_full)) == nrow(govZA_tweets_full)]
# take out columns that have list values
govZA_tweets <- govZA_tweets %>%
  select_if(~!is.list(.))

# write to csv
write.csv(govZA_tweets, "data/govZA_tweets.csv")
```

--------------------------------------------------
USA
--------------------------------------------------

# cnnbrk
```{r}
cnnbrk_tweets_full <- get_timeline("cnnbrk", n=n_tweets)
```
```{r}
# take out columns consisting of NA values
cnnbrk_tweets <- cnnbrk_tweets_full[, colSums(!is.na(cnnbrk_tweets_full)) == nrow(cnnbrk_tweets_full)]
# take out columns that have list values
cnnbrk_tweets <- cnnbrk_tweets %>%
  select_if(~!is.list(.))

# write to csv
write.csv(cnnbrk_tweets, "data/cnnbrk_tweets.csv")
```

# FoxNews
```{r}
FoxNews_tweets_full <- get_timeline("FoxNews", n=n_tweets)
```
```{r}
# take out columns consisting of NA values
FoxNews_tweets <- FoxNews_tweets_full[, colSums(!is.na(FoxNews_tweets_full)) == nrow(FoxNews_tweets_full)]
# take out columns that have list values
FoxNews_tweets <- FoxNews_tweets %>%
  select_if(~!is.list(.))

# write to csv
write.csv(FoxNews_tweets, "data/FoxNews_tweets.csv")
```

--------------------------------------------------
UK
--------------------------------------------------

# BBC Breaking
```{r}
BBC_tweets_full <- get_timeline("bbcbreaking", n=n_tweets)
```
```{r}
# take out columns consisting of NA values
BBC_tweets <- BBC_tweets_full[, colSums(!is.na(BBC_tweets_full)) == nrow(BBC_tweets_full)]
# take out columns that have list values
BBC_tweets <- BBC_tweets %>%
  select_if(~!is.list(.))

# write to csv
write.csv(BBC_tweets, "data/BBCbreaking_tweets.csv")
```

--------------------------------------------------
Global
--------------------------------------------------

# Time
```{r}
time_tweets_full <- get_timeline("time", n=n_tweets)
```
```{r}
# take out columns consisting of NA values
time_tweets <- time_tweets_full[, colSums(!is.na(time_tweets_full)) == nrow(time_tweets_full)]
# take out columns that have list values
time_tweets <- time_tweets %>%
  select_if(~!is.list(.))

# write to csv
write.csv(time_tweets, "data/time_tweets.csv")
```

# The Economist
```{r}
economist_tweets_full <- get_timeline("theeconomist", n=n_tweets)
```
```{r}
# take out columns consisting of NA values
economist_tweets <- economist_tweets_full[, colSums(!is.na(economist_tweets_full)) == nrow(economist_tweets_full)]
# take out columns that have list values
economist_tweets <- economist_tweets %>%
  select_if(~!is.list(.))

# write to csv
write.csv(economist_tweets, "data/economist_tweets.csv")
```

# BBC World
```{r}
bbcworld_tweets_full <- get_timeline("bbcworld", n=n_tweets)
```
```{r}
# take out columns consisting of NA values
bbcworld_tweets <- bbcworld_tweets_full[, colSums(!is.na(bbcworld_tweets_full)) == nrow(bbcworld_tweets_full)]
# take out columns that have list values
bbcworld_tweets <- bbcworld_tweets %>%
  select_if(~!is.list(.))

# write to csv
write.csv(bbcworld_tweets, "data/bbcworld_tweets.csv")
```

# AP
```{r}
AP_tweets_full <- get_timeline("AP", n=n_tweets)
```
```{r}
# take out columns consisting of NA values
AP_tweets <- AP_tweets_full[, colSums(!is.na(AP_tweets_full)) == nrow(AP_tweets_full)]
# take out columns that have list values
AP_tweets <- AP_tweets %>%
  select_if(~!is.list(.))

# write to csv
write.csv(AP_tweets, "data/AP_tweets.csv")
```

--------------------------------------------------
SA
--------------------------------------------------

# Daily Maverick
```{r}
DailyMav_tweets_full <- get_timeline("DailyMaverick", n=n_tweets)
```
```{r}
# take out columns consisting of NA values
DailyMav_tweets <- DailyMav_tweets_full[, colSums(!is.na(DailyMav_tweets_full)) == nrow(DailyMav_tweets_full)]
# take out columns that have list values
DailyMav_tweets <- DailyMav_tweets %>%
  select_if(~!is.list(.))

# write to csv
write.csv(DailyMav_tweets, "data/DailyMav_tweets.csv")
```

# Media 24
```{r}
Media24_tweets_full <- get_timeline("Media24", n=n_tweets)
```
```{r}
# take out columns consisting of NA values
Media24_tweets <- Media24_tweets_full[, colSums(!is.na(Media24_tweets_full)) == nrow(Media24_tweets_full)]
# take out columns that have list values
Media24_tweets <- Media24_tweets %>%
  select_if(~!is.list(.))

# write to csv
write.csv(Media24_tweets, "data/Media24_tweets.csv")
```

# EWN
```{r}
EWN_tweets_full <- get_timeline("EwnUpdates", n=n_tweets)
```
```{r}
# take out columns consisting of NA values
EWN_tweets <- EWN_tweets_full[, colSums(!is.na(EWN_tweets_full)) == nrow(EWN_tweets_full)]
# take out columns that have list values
EWN_tweets <- EWN_tweets %>%
  select_if(~!is.list(.))

# write to csv
write.csv(EWN_tweets, "data/EWN_tweets.csv")
```

# News24
```{r}
News24_tweets_full <- get_timeline("News24", n=n_tweets)
```
```{r}
# take out columns consisting of NA values
News24_tweets <- News24_tweets_full[, colSums(!is.na(News24_tweets_full)) == nrow(News24_tweets_full)]
# take out columns that have list values
News24_tweets <- News24_tweets %>%
  select_if(~!is.list(.))

# write to csv
write.csv(News24_tweets, "data/News24_tweets.csv")
```

# Cape Talk
```{r}
CapeTalk_tweets_full <- get_timeline("CapeTalk", n=n_tweets)
```
```{r}
# take out columns consisting of NA values
CapeTalk_tweets <- CapeTalk_tweets_full[, colSums(!is.na(CapeTalk_tweets_full)) == nrow(CapeTalk_tweets_full)]
# take out columns that have list values
CapeTalk_tweets <- CapeTalk_tweets %>%
  select_if(~!is.list(.))

# write to csv
write.csv(CapeTalk_tweets, "data/CapeTalk_tweets.csv")
```

# SABC news
```{r}
SABCNews_tweets_full <- get_timeline("SABCNews", n=n_tweets)
```
```{r}
# take out columns consisting of NA values
SABCNews_tweets <- SABCNews_tweets_full[, colSums(!is.na(SABCNews_tweets_full)) == nrow(SABCNews_tweets_full)]
# take out columns that have list values
SABCNews_tweets <- SABCNews_tweets %>%
  select_if(~!is.list(.))

# write to csv
write.csv(SABCNews_tweets, "data/SABCNews_tweets.csv")
```

# Cape Argus news
```{r}
CapeArgus_tweets_full <- get_timeline("TheCapeArgus", n=n_tweets)
```
```{r}
# take out columns consisting of NA values
CapeArgus_tweets <- CapeArgus_tweets_full[, colSums(!is.na(CapeArgus_tweets_full)) == nrow(CapeArgus_tweets_full)]
# take out columns that have list values
CapeArgus_tweets <- CapeArgus_tweets %>%
  select_if(~!is.list(.))

# write to csv
write.csv(CapeArgus_tweets, "data/CapeArgus_tweets.csv")
```