---
title: "Sentiment analysis"
output: html_notebook
---

# TODO
* add custom sentiment to vader analysis
* Cape_Talk was removed due to 5 datasets throwing [this](https://stackoverflow.com/questions/15363076/error-in-gzfilefile-wb-cannot-open-the-connection-or-compressed-file) error when applying `apply_vader()` (was a bit too much to handle) 

<!----------------------------------------------------------------------------------------------------------------------------------------------------->
<!-- Setup -->
<!----------------------------------------------------------------------------------------------------------------------------------------------------->

```{r set colours}
# Stellenbosch branding manual colours:
# http://stbweb01.stb.sun.ac.za/centenarybrandtoolkit/SU_Brand_Manual_2019.pdf 
arts_orange <- "#FF8F1C"
law_winered <- "#9e2629"
theology_purple <- "#84329B"
education_darkblue <- "#326295"
agri_green <- "#509e2f"
med_bluegreen <- "#006163"
military_salmon <- "#e56a54"
science_red <- "#cb333b"
ems_lightblue <- "#2dccd3"
engineering_yellow <- "#eaaa00"
maroon <- "#60223b"
mustard <- "#F1B434"
darkgrey <- "#333333"
lightgrey <- "#8c979a"
black <- "#000000"

su_colors <- c(arts_orange, law_winered, theology_purple, education_darkblue, agri_green, med_bluegreen, military_salmon, science_red, ems_lightblue, engineering_yellow, maroon, mustard, darkgrey, lightgrey, black)

# microsoft sharepoint main colours
# https://docs.microsoft.com/en-us/sharepoint/dev/design/themes-colors
ms_red <- "#A4262C"
ms_orange <- "#CA5010"
ms_gold <- "#8F7034"
ms_green <- "#407855"
ms_teal <- "#038387"
ms_blue <- "#0078d4"
ms_darkblue <- "#40587C"
ms_indigo <- "#4052AB"
ms_plum <- "#854085"
ms_purple <- "#8764B8"
ms_coolgrey <- "#737373"
ms_warmgrey <- "#867365"

ms_colors <- c(ms_red, ms_orange, ms_gold, ms_green, ms_teal, ms_blue, ms_darkblue, ms_indigo, ms_plum, ms_purple, ms_coolgrey, ms_warmgrey)

# colour picker: http://tristen.ca/hcl-picker/#/hlc/10/1.02/EBB350/48231C
color_picker <- c("#EBB350", "#ABB14C", "#6EA85F", "#3A9976", "#248686", "#3F6F85", "#585674", "#623F57", "#5B2E37", "#48231C")

# palette generator: https://learnui.design/tools/data-color-picker.html#palette
palette_generator <- c("#003f5c", "#665191", "#d45087", "#ff7c43", "#ffa600")
```

```{r custom themes}
custom_column_basic_theme <- function () { 
    theme_minimal(base_size=12, base_family="Avenir") +
        theme(
            panel.background  = element_blank(),
            panel.grid.minor = element_blank(),
            legend.position="none", # no legend
            plot.title = element_text(size = 10, hjust = 0),
            plot.caption = element_text(size = 8, hjust = 0)
        )
}

custom_line_basic_theme <- function () { 
    theme_minimal(base_size=12, base_family="Avenir") +
        theme(
            panel.background  = element_blank(),
            panel.grid.minor = element_blank(),
            plot.title = element_text(size = 10, hjust = 0),
            plot.subtitle = element_text(size = 8, hjust = 0),
            plot.caption = element_text(size = 8, hjust = 0)
        )
}
```

```{r import libraries}
library(tidyverse)
library(vader) # sentiment analysis
library(tidytext)
library(lubridate) # date conversion
library(RcppRoll) # rolling average
library(ggplot2)
```

```{r extract relevant data from read in csv}
extract_relevant_data <- function(df) {
  return(df %>% select(status_id, screen_name, created_at, statuses_count, is_retweet, favorite_count, retweet_count, followers_count, friends_count, text))
}
```

```{r read South Africa data}
DailyMav_tweets <- extract_relevant_data(read.csv("data/dailymaverick.csv"))
EWN_tweets <- extract_relevant_data(read.csv("data/ewnupdates.csv"))
News24_tweets <- extract_relevant_data(read.csv("data/news24.csv"))
SABCNews_tweets <- extract_relevant_data(read.csv("data/sabcnews.csv"))
# combine tweets into a list of dataframes
media_outlet_list <- list(DailyMav_tweets, EWN_tweets, News24_tweets, SABCNews_tweets)

head(media_outlet_list[1])
```
```{r read Global data}
nytimes_tweets <- extract_relevant_data(read.csv("data/nytimes.csv"))
AP_tweets <- extract_relevant_data(read.csv("data/ap.csv"))
bbcworld_tweets <- extract_relevant_data(read.csv("data/bbcworld.csv"))
economist_tweets <- extract_relevant_data(read.csv("data/theeconomist.csv"))
# combine tweets into a list of dataframes
global_media_outlet_list <- list(nytimes_tweets, AP_tweets, bbcworld_tweets, economist_tweets)

head(global_media_outlet_list[1])
```

<!----------------------------------------------------------------------------------------------------------------------------------------------------->
<!-- Data Wrangling -->
<!----------------------------------------------------------------------------------------------------------------------------------------------------->


```{r extract tweets related to covid and combine covid tweets into a list}
# extract covid tweets function
get_covid_tweets <- function(df) {
relevant_df <-  df[grepl("covid", df[["text"]]) | 
                  grepl("Covid", df[["text"]]) |
                  grepl("corona", df[["text"]]) |
                  grepl("Corona", df[["text"]]) |
                  grepl("Pandemic", df[["text"]]) |
                  grepl("pandemic", df[["text"]]), ]
relevant_df <- relevant_df %>%
  mutate(created_at = ymd_hms(created_at))
return(relevant_df)
}

# South African: combine relevant tweets for all media outlets into list
covid_tweets <- list(get_covid_tweets(DailyMav_tweets), 
                     get_covid_tweets(EWN_tweets), 
                     get_covid_tweets(News24_tweets), 
                     get_covid_tweets(SABCNews_tweets))

# Global: combine relevant tweets for all media outlets into list
global_covid_tweets <- list(get_covid_tweets(nytimes_tweets), 
                            get_covid_tweets(AP_tweets),
                            get_covid_tweets(bbcworld_tweets), 
                            get_covid_tweets(economist_tweets))
```

```{r tidy tweets - remove stopwords and clean data}
my_stopwords <- c("covid", "covid19", "corona", "coronavirus")

clean_tweets <- function(df) {
# remove stop words, links, special characters
cleaned_tweets <- df %>%
  unnest_tokens(word, text) %>%
  filter(!word %in% stop_words$word,
         !word %in% my_stopwords,
         !word %in% str_remove_all(stop_words$word, "'"),
         !str_starts(word, "http"), # remove links
         !str_starts(word, "@"), # remove mentions
         str_detect(word, "[a-z]")) %>%
  mutate(word = gsub("\\d+", "", word)) %>% # remove numbers
  # group words back together (creating sentences) according to their twitter_id
  group_by(status_id, screen_name, created_at, retweet_count, favorite_count) %>%
  summarize(text=str_c(word, collapse = " ")) %>%
  ungroup()

return(cleaned_tweets)
}

# South African: apply cleaning function to all media outlets
tidy_tweets <- lapply(covid_tweets, clean_tweets)
head(tidy_tweets)

# Global: apply cleaning function to all media outlets
global_tidy_tweets <- lapply(global_covid_tweets, clean_tweets)
head(global_tidy_tweets)
```

```{r apply vader sentiment analysis to list of cleaned covid tweets}
apply_vader <- function(df) {
  return(vader_df(df$text))
}
# South African: apply vader analysis to media outlets
vader_analysis <- lapply(tidy_tweets, apply_vader)
head(vader_analysis)

# Global: apply vader analysis to media outlets
global_vader_analysis <- lapply(global_tidy_tweets, apply_vader)
head(global_vader_analysis)
```


```{r get sentiment mean per oulet}
# get names of media outlets
name <- unlist(lapply(media_outlet_list, function(df) {return(df$screen_name[1])}))
global_name <- unlist(lapply(global_media_outlet_list, function(df) {return(df$screen_name[1])}))

get_sentiment_mean <- function(df) {
  return(mean(df$compound))
}
# South African: get average sentiment for media outlets
sentiment_mean_per_outlet <- unlist(lapply(vader_analysis, get_sentiment_mean))
overall_sentiment_per_outlet <- data.frame(name, sentiment_mean_per_outlet)
head(overall_sentiment_per_outlet)

# Global: get average sentiment for media outlets
global_sentiment_mean_per_outlet <- unlist(lapply(global_vader_analysis, get_sentiment_mean))
global_overall_sentiment_per_outlet <- data.frame(global_name, global_sentiment_mean_per_outlet)
head(global_overall_sentiment_per_outlet)
```
```{r get overall sentiment for all outlets}
# South African: total overall sentiment
total_overall_sentiment <- sum(overall_sentiment_per_outlet$sentiment_mean_per_outlet)
head(total_overall_sentiment)

# Global: total overall sentiment
global_total_overall_sentiment <- sum(global_overall_sentiment_per_outlet$global_sentiment_mean_per_outlet)
head(global_total_overall_sentiment)
```


# Sentiment on top x tweets
```{r set number of tweets to be extracted}
NUM_TWEETS <- 10
```

```{r sentiment analysis on top retweeted tweets per media outlet}
# TODO need to plot nicely (as table?)

# get top NUM_TWEETS retweeted tweets per media outlet
get_top_retweets <- function(df) {
  text <- df %>%
    arrange(desc(retweet_count)) %>% 
    slice(1:NUM_TWEETS) %>% 
    select(status_id, screen_name, created_at, retweet_count, text)
  return(text)
}

# South African: apply sentiment analysis on top NUM_TWEETS user retweeted tweets per media outlet
top_retweets <- lapply(tidy_tweets, get_top_retweets)
top_retweets_vader_analysis <- lapply(top_retweets, apply_vader)

# Global: apply sentiment analysis on top NUM_TWEETS user retweeted tweets per media outlet
global_top_retweets <- lapply(global_tidy_tweets, get_top_retweets)
global_top_retweets_vader_analysis <- lapply(global_top_retweets, apply_vader)

# South African: get average sentiment for top retweets per media outlet
top_retweets_sentiment_mean <- unlist(lapply(top_retweets_vader_analysis, get_sentiment_mean))
top_retweets_sentiment_per_outlet <- data.frame(name, top_retweets_sentiment_mean)
head(top_retweets_sentiment_per_outlet)

# Global: get average sentiment for top retweets per media outlet
global_top_retweets_sentiment_mean <- unlist(lapply(global_top_retweets_vader_analysis, get_sentiment_mean))
global_top_retweets_sentiment_per_outlet <- data.frame(global_name, global_top_retweets_sentiment_mean)
head(global_top_retweets_sentiment_per_outlet)
```



```{r sentiment analysis on top favourited tweets per media outlet}
# TODO need to plot nicely (as table?)

# get top NUM_TWEETS favourited tweets per media outlet
get_top_favorited_tweets <- function(df) {
  text <- df %>%
    arrange(desc(favorite_count)) %>% 
    slice(1:NUM_TWEETS) %>% 
    select(status_id, screen_name, created_at, favorite_count, text)
  return(text)
}
# South Africa: apply sentiment analysis on top NUM_TWEETS favourited tweets per media outlet
top_favourited <- lapply(tidy_tweets, get_top_favorited_tweets)
top_favourited_vader_analysis <- lapply(top_favourited, apply_vader)

# Global: apply sentiment analysis on top NUM_TWEETS favourited tweets per media outlet
global_top_favourited <- lapply(global_tidy_tweets, get_top_favorited_tweets)
global_top_favourited_vader_analysis <- lapply(global_top_favourited, apply_vader)

# South Africa: get average sentiment for top favourited tweets per media outlet
top_favourited_sentiment_mean <- unlist(lapply(top_favourited_vader_analysis, get_sentiment_mean))
top_favourited_sentiment_per_outlet <- data.frame(name, top_favourited_sentiment_mean)
head(top_favourited_sentiment_per_outlet)

# Global: get average sentiment for top favourited tweets per media outlet
global_top_favourited_sentiment_mean <- unlist(lapply(global_top_favourited_vader_analysis, get_sentiment_mean))
global_top_favourited_sentiment_per_outlet <- data.frame(global_name, global_top_favourited_sentiment_mean)
head(global_top_favourited_sentiment_per_outlet)
```


# Sentiment analysis over time

```{r set rolling average timeframe}
ROLLING_AVERAGE_TIME <- 30 # month
```

```{r sentiment analysis over time with rolling avg}
# want to add the vader compound column (in a list of dataframes) to tidy_tweets (a list of dataframes)
for (i in seq(tidy_tweets)) {
  tidy_tweets[[i]]["compound"] <- vader_analysis[[i]]["compound"]
}

# calculate 7-day rolling average of compound
for (i in seq(tidy_tweets)) {
  tidy_tweets[[i]] <- tidy_tweets[[i]] %>% 
    mutate(rolling_avg = roll_mean(compound, n=ROLLING_AVERAGE_TIME, fill = NA, align = "right"))
}
tidy_tweets
```
```{r global sentiment analysis over time with rolling avg}
# want to add the vader compound column (in a list of dataframes) to tidy_tweets (a list of dataframes)
for (i in seq(global_tidy_tweets)) {
  global_tidy_tweets[[i]]["compound"] <- global_vader_analysis[[i]]["compound"]
}

# calculate 7-day rolling average of compound
for (i in seq(global_tidy_tweets)) {
  global_tidy_tweets[[i]] <- global_tidy_tweets[[i]] %>% 
    mutate(rolling_avg = roll_mean(compound, n=ROLLING_AVERAGE_TIME, fill = NA, align = "right"))
}
global_tidy_tweets
```



<!----------------------------------------------------------------------------------------------------------------------------------------------------->
<!-- Data Visualisation (South Africa)-->
<!----------------------------------------------------------------------------------------------------------------------------------------------------->

```{r plot total overall sentiment}
# TODO: make a valuebox or something?
total_overall_sentiment
```


```{r plot overall sentiment per organisation on covid-19}
ggplot(overall_sentiment_per_outlet, aes(name, sentiment_mean_per_outlet, fill=name)) +
  geom_col() +
  labs(title = "Overall sentiment per organisation on covid-19",
       x=NULL,
       y="Vader Sentiment Score") +
  scale_fill_manual(values = ms_colors) +
  custom_column_basic_theme()
```

```{r plot sentiment on Top x retweeted tweets per organisation (that users retweet)}
ggplot(top_retweets_sentiment_per_outlet, aes(name, top_retweets_sentiment_mean, fill=name)) +
  geom_col() +
  labs(title = paste("Sentiment of Top", NUM_TWEETS, "retweeted tweets per organisation on covid-19"),
       x=NULL,
       y="Vader Sentiment Score") +
  scale_fill_manual(values = ms_colors) +
  custom_column_basic_theme()
```

```{r plot sentiment on Top x favourited tweets per organisation}
ggplot(top_favourited_sentiment_per_outlet, aes(name, top_favourited_sentiment_mean, fill=name)) +
  geom_col() +
  labs(title = paste("Sentiment of Top", NUM_TWEETS, "favourited tweets per organisation on covid-19"),
       x=NULL,
       y="Vader Sentiment Score") +
  scale_fill_manual(values = ms_colors) +
  custom_column_basic_theme()
```



```{r plot sentiment per organisation over time on covid-19}
# TODO: want to apply log scale (not working due to time format)
ggplot(bind_rows(tidy_tweets, .id="df"), aes(created_at, rolling_avg, colour=screen_name)) + 
  geom_line() +
  labs(title= "Sentiment over time per media outlet",
       subtitle = paste("A rolling average of", ROLLING_AVERAGE_TIME, "is used."),
       color="Media outlet",
       x = NULL,
       y = "Vader Sentiment Score") +
  # TODO: not working due to date being in POSIXt format
  # scale_x_log10() + 
  scale_colour_manual(values = ms_colors) +
  custom_line_basic_theme()
```

<!----------------------------------------------------------------------------------------------------------------------------------------------------->
<!-- Data Visualisation (Global)-->
<!----------------------------------------------------------------------------------------------------------------------------------------------------->

```{r plot global total overall sentiment}
# TODO: make a valuebox or something?
global_total_overall_sentiment
```


```{r plot global overall sentiment per organisation on covid-19}
ggplot(global_overall_sentiment_per_outlet, aes(global_name, global_sentiment_mean_per_outlet, fill=global_name)) +
  geom_col() +
  labs(title = "Global: Overall sentiment per organisation on covid-19",
       x=NULL,
       y="Vader Sentiment Score") +
  scale_fill_manual(values = rev(ms_colors)) +
  custom_column_basic_theme()
```

```{r plot globalsentiment on Top x retweeted tweets per organisation (that users retweet)}
ggplot(global_top_retweets_sentiment_per_outlet, aes(global_name, global_top_retweets_sentiment_mean, fill=global_name)) +
  geom_col() +
  labs(title = paste("Global: Sentiment of Top", NUM_TWEETS, "retweeted tweets per organisation on covid-19"),
       x=NULL,
       y="Vader Sentiment Score") +
  scale_fill_manual(values = rev(ms_colors)) +
  custom_column_basic_theme()
```

```{r plot global sentiment on Top x favourited tweets per organisation}
ggplot(global_top_favourited_sentiment_per_outlet, aes(global_name, global_top_favourited_sentiment_mean, fill=global_name)) +
  geom_col() +
  labs(title = paste("Global: Sentiment of Top", NUM_TWEETS, "favourited tweets per organisation on covid-19"),
       x=NULL,
       y="Vader Sentiment Score") +
  scale_fill_manual(values = rev(ms_colors)) +
  custom_column_basic_theme()
```



```{r plot global sentiment per organisation over time on covid-19}
# TODO: want to apply log scale (not working due to time format)
ggplot(bind_rows(global_tidy_tweets, .id="df"), aes(created_at, rolling_avg, colour=screen_name)) + 
  geom_line() +
  labs(title= "Global: Sentiment over time per media outlet",
       subtitle = paste("A rolling average of", ROLLING_AVERAGE_TIME, "is used."),
       color="Media outlet",
       x = NULL,
       y = "Vader Sentiment Score") +
  # TODO: not working due to date being in POSIXt format
  # scale_x_log10() + 
  scale_colour_manual(values = rev(ms_colors)) +
  custom_line_basic_theme()
```


