---
title: "R Notebook"
output: html_notebook
---

## adapted from TidyTextMining Ch 6

<!----------------------------------------------------------------------------------------------------------------------------------------------------->
<!-- Setup -->
<!----------------------------------------------------------------------------------------------------------------------------------------------------->

<!-- Set colours according to Stellenbosch Branding manual-->
<!-- http://stbweb01.stb.sun.ac.za/centenarybrandtoolkit/SU_Brand_Manual_2019.pdf -->
```{r set colours}
dailymav_colour <- "#FF8F1C" # Daily Maveric - arts_orange
capetalk_colour <- "#9e2629" # Cape Talk - law_winered
sabc_colour <- "#84329B" # SABC News - theology_purple
news24_colour <- "#326295" # News24 - education_darkblue
ewn_colour <- "#509e2f" # EWN - agri_green

# other colours to use
med_bluegreen <- "#006163"
military_salmon <- "#e56a54"
science_red <- "#cb333b"
ems_lightblue <- "#2dccd3"
maroon <- "#60223b"
mustard <- "#F1B434"
darkgrey <- "#333333"
lightgrey <- "#8c979a"
black <- "#000000"
engineering_yellow <- "#eaaa00"
```

```{r custom themes}
custom_column_basic_theme <- function () { 
    theme_minimal(base_size=12, base_family="Avenir") +
        theme(
            panel.background  = element_blank(),
            panel.grid.minor = element_blank(),
            legend.position="none", # no legend
            plot.title = element_text(size = 10, hjust = 0),
            plot.caption = element_text(size = 8, hjust = 0)
        )
}

custom_line_basic_theme <- function () { 
    theme_minimal(base_size=12, base_family="Avenir") +
        theme(
            panel.background  = element_blank(),
            panel.grid.minor = element_blank(),
            plot.title = element_text(size = 10, hjust = 0),
            plot.subtitle = element_text(size = 8, hjust = 0),
            plot.caption = element_text(size = 8, hjust = 0)
        )
}
```

```{r import libraries}
library(tidytext)
library(lubridate)
library(dplyr)
library(stringr)
library(tidyr)
library(ggplot2)
library(topicmodels) # NOTE: (Gina) need to install gsl package first with sudo apt-get install libgsl0-dev
# Gina added
library(reshape2) # threw an error when assigning org_lda for not having this package
library(vader) # sentiment analysis
```


<!----------------------------------------------------------------------------------------------------------------------------------------------------->
<!-- Topic Modeling for SA Media Agencies -->
<!----------------------------------------------------------------------------------------------------------------------------------------------------->

```{r read data}
SABCNews_tweets <- read.csv("data/SABCNews_tweets.csv")
DailyMav_tweets <- read.csv("data/DailyMav_tweets.csv")
CapeTalk_tweets <- read.csv("data/CapeTalk_tweets.csv")
EWN_tweets <- read.csv("data/EWN_tweets.csv")
News24_tweets <- read.csv("data/News24_tweets.csv")

# TODO: combine into list as with seniment analysis
# media_outlet_list <- list(DailyMav_tweets, EWN_tweets, News24_tweets, SABCNews_tweets) # Gina added
```


```{r extract tweets related to covid}
filter_relevant_tweets <- function(tweets) {
  relevant_tweets <- tweets[grepl("covid", tweets[["text"]]) | 
                  grepl("Covid", tweets[["text"]]) |
                  grepl("corona", tweets[["text"]]) |
                  grepl("Corona", tweets[["text"]]) |
                  grepl("Pandemic", tweets[["text"]]) |
                  grepl("pandemic", tweets[["text"]]), ]
relevant_tweets <- relevant_tweets %>%
  mutate(created_at = ymd_hms(created_at))
}

# TODO: combine into list as with sentiment analysis
relevant_SABC <- filter_relevant_tweets(SABCNews_tweets)
relevant_DM <- filter_relevant_tweets(DailyMav_tweets)
relevant_CapeTalk <- filter_relevant_tweets(CapeTalk_tweets)
relevant_EWN <- filter_relevant_tweets(EWN_tweets)
relevant_News24 <- filter_relevant_tweets(News24_tweets)
```

```{r combine all tweets into one dataframe}
# combine all tweets into one dataframe
tweets <- bind_rows(relevant_SABC %>% mutate(user = "SABC"),
                    relevant_DM %>% mutate(user = "DailyMaverick"),
                    relevant_CapeTalk %>% mutate(user = "CapeTalk"),
                    relevant_EWN %>% mutate(user = "EWN"),
                    relevant_News24 %>% mutate(user = "News24"))
```

```{r tidy tweets - remove stopwords and clean data}
clean_tweets <- function(tweets_in) {
  # define custom stopwords
  my_stopwords <- c("covid", "covid19", "corona", "coronavirus")
  # remove stopwords
  tidy_tweets <- tweets_in %>% 
    unnest_tokens(word, text, token = "tweets") %>%
    filter(!word %in% stop_words$word,
           !word %in% my_stopwords,
           !word %in% str_remove_all(stop_words$word, "'"),
           !str_starts(word, "http"), # remove links
           !str_starts(word, "@"), # remove mentions
           str_detect(word, "[a-z]")) %>%
    mutate(word = gsub("\\d+", "", word)) %>% # remove numbers
    select(screen_name, created_at, name, location, user, word)
  
  return(tidy_tweets)
}

tidy_tweets <- clean_tweets(tweets)
```


# Topic Modelling
```{r apply topic modelling to get overall topics}
overall_topics <- function(tidy_tweets_in, nr_of_topics) {
  # word count by media organisation
  word_counts <- tidy_tweets_in %>%
    select(user, word, created_at) %>%
    count(user, word, sort = TRUE) %>%
    ungroup()
  
  # create document term matrix
  # (treating all tweets from one organisation as one document)
  orgs_dtm <- word_counts %>%
    cast_dtm(user, word, n)
  
  # define number of topics
  k_topics = nr_of_topics
  # apply topic modelling
  orgs_lda <- LDA(orgs_dtm, k = k_topics, control = list(seed = 1234))
  
  orgs_topics_overall <- tidy(orgs_lda, matrix = "beta")
  
  return(orgs_topics_overall)
}
```

```{r plot topics}
model_topics_overall <- function(tidy_tweets_in, nr_of_topics) {
  
  orgs_topics <- overall_topics(tidy_tweets_in, nr_of_topics)
  
  # find top words per topic
  top_terms <- orgs_topics %>%
    group_by(topic) %>%
    slice_max(beta, n = 5) %>% 
    ungroup() %>%
    arrange(topic, -beta)
  
  # plot top terms per topic
  top_terms %>%
    mutate(term = reorder_within(term, beta, topic)) %>%
    ggplot(aes(beta, term, fill = factor(topic))) +
    geom_col(show.legend = FALSE) +
    facet_wrap(~ topic, scales = "free") +
    scale_y_reordered()
}
```

```{r}
#topics_overall <- overall_topics(tidy_tweets, 4) %>%
#  pivot_wider(names_from = topic, values_from = beta)
```

```{r extract top words per topic}
top_words_per_topic <- function(topics, words_per_topic) {
  return(topics%>%
  group_by(topic) %>%
  slice_max(beta, n = words_per_topic) %>%
  ungroup() %>%
  arrange(topic, -beta))
}
```

```{r get overall topics for all media outlets for entire time period}
# top words per topic (for sentiment analysis)
nr_of_topics <- 4
words_per_topic <- 200
topics_overall <- top_words_per_topic(overall_topics(tidy_tweets, nr_of_topics), words_per_topic)
```

```{r}
model_topics_overall(tidy_tweets, nr_of_topics)
```

# topic modelling over time

```{r get topics per month}
monthly_topics <- function(tidy_tweets_in, past_month, nr_topics) {
  # word count by media organisation for specified month
  word_counts <- tidy_tweets_in %>%
    # create time bins (monthly)
    mutate(time_floor = floor_date(created_at, unit = "month")) %>%
    select(user, word, time_floor) %>%
    # filter to specified month
    filter(time_floor == as.Date(past_month)) %>%
    count(user, word, sort = TRUE) %>%
    ungroup()
    
  # create document term matrix
  # (treating all tweets from one organisation as one document)
  orgs_dtm <- word_counts %>%
    cast_dtm(user, word, n)

  # apply topic modelling
  orgs_lda <- LDA(orgs_dtm, k = nr_topics, control = list(seed = 1234))

  orgs_topics_month <- tidy(orgs_lda, matrix = "beta")
  
  return(orgs_topics_month)
}
```

```{r plot topics per month}
# past_month being the full date of the first day of that month - eg "2021-06-01" for June
model_topics_of_month <- function(tidy_tweets_in, past_month, nr_topics) {

  #topics for the month
  orgs_topics <- monthly_topics(tidy_tweets_in, past_month, nr_topics)

  # find top words per topic
  top_terms <- orgs_topics %>%
    group_by(topic) %>%
    slice_max(beta, n = 5) %>% 
    ungroup() %>%
    arrange(topic, -beta)

  # plot top terms per topic
  top_terms %>%
    mutate(term = reorder_within(term, beta, topic)) %>%
    ggplot(aes(beta, term, fill = factor(topic))) +
    geom_col(show.legend = FALSE) +
    labs(title = paste("Topics for month starting", past_month)) +
    facet_wrap(~ topic, scales = "free") +
    scale_y_reordered()
}
```

```{r get overall topics for all media outlets per month}
# top words per topic (for sentiment analysis)
nr_of_topics <- 4
words_per_topic <- 200
# TODO: where is June_topics used?
June_topics <- top_words_per_topic(monthly_topics(tidy_tweets, "2021-06-01", 4), words_per_topic)

# plot
model_topics_of_month(tidy_tweets, "2021-06-01", 4)
model_topics_of_month(tidy_tweets, "2021-05-01", 2)
# note: previous months have fewer topics because SABC only has data for June, anything before is only Daily Maverick
model_topics_of_month(tidy_tweets, "2021-04-01", 2)
```

```{r Gina added: create list with topics per month}
NUM_TOPICS_MONTH <- 4
NUM_TOPICS_MONTH_REDUCED <- 2 # some months have less topics due to less data being available

# TODO: Should indicate date on dataframe such that we know which month is associated with which dataframe in topics_per_month
# TODO: optimise this in some way with a loop?
topics_per_month_list <- list(
  top_words_per_topic(monthly_topics(tidy_tweets, "2021-04-01", NUM_TOPICS_MONTH_REDUCED), words_per_topic),
  top_words_per_topic(monthly_topics(tidy_tweets, "2021-05-01", NUM_TOPICS_MONTH), words_per_topic),
  top_words_per_topic(monthly_topics(tidy_tweets, "2021-06-01", NUM_TOPICS_MONTH), words_per_topic)
)
topics_per_month_list
```


# topic modelling per organisation

```{r get topics per organisation}
org_topics <- function(tidy_tweets_in, org, nr_topics) {
  # word count for specified media organisation
  word_counts <- tidy_tweets %>%
    select(user, word) %>%
    # filter to specified org
    filter(user == org) %>%
    count(user, word, sort = TRUE) %>%
    ungroup()
    
  # create document term matrix
  # (treating all tweets from one organisation as one document)
  orgs_dtm <- word_counts %>%
    cast_dtm(user, word, n)

  # apply topic modelling
  orgs_lda <- LDA(orgs_dtm, k = nr_topics, control = list(seed = 1234))

  org_topics <- tidy(orgs_lda, matrix = "beta")
  
  return(org_topics)
}
```

```{r plot topics per organisation}
# org being the name of the media agency as found in the tidy_tweets dataframe
model_topics_of_org <- function(tidy_tweets_in, org, nr_topics) {

  # topics for org
  orgs_topics <- org_topics(tidy_tweets_in, org, nr_topics)

  # find top words per topic
  top_terms <- orgs_topics %>%
    group_by(topic) %>%
    slice_max(beta, n = 5) %>% 
    ungroup() %>%
    arrange(topic, -beta)

  # plot top terms per topic
  top_terms %>%
    mutate(term = reorder_within(term, beta, topic)) %>%
    ggplot(aes(beta, term, fill = factor(topic))) +
    geom_col(show.legend = FALSE) +
    labs(title = paste("Topics for ", org)) +
    facet_wrap(~ topic, scales = "free") +
    scale_y_reordered()
}
```

```{r}
# top words per topic (for sentiment analysis)
n_topics <- 3
words_per_topic <- 200
# TODO: where is DailyMav_topics used?
DailyMav_topics <- top_words_per_topic(org_topics(tidy_tweets, "DailyMaverick", n_topics), words_per_topic)

# plot
model_topics_of_org(tidy_tweets, "DailyMaverick", 3)
model_topics_of_org(tidy_tweets, "SABC", 2)
model_topics_of_org(tidy_tweets, "CapeTalk", 2)
model_topics_of_org(tidy_tweets, "EWN", 2)
model_topics_of_org(tidy_tweets, "News24", 2)
```

```{r Gina added: create list with topics per media outlet}
NUM_TOPICS_OUTLET <- 3
NUM_TOPICS_OUTLET_REDUCED <- 2

# TODO: Should indicate date on dataframe such that we know which month is associated with which dataframe in topics_per_outlet
# TODO: optimise this in some way with a loop?
topics_per_outlet_list <- list(
  top_words_per_topic(org_topics(tidy_tweets, "DailyMaverick", NUM_TOPICS_OUTLET), words_per_topic),
  top_words_per_topic(org_topics(tidy_tweets, "SABC", NUM_TOPICS_OUTLET_REDUCED), words_per_topic),
  top_words_per_topic(org_topics(tidy_tweets, "CapeTalk", NUM_TOPICS_OUTLET_REDUCED), words_per_topic),
  top_words_per_topic(org_topics(tidy_tweets, "EWN", NUM_TOPICS_OUTLET_REDUCED), words_per_topic),
  top_words_per_topic(org_topics(tidy_tweets, "News24", NUM_TOPICS_OUTLET_REDUCED), words_per_topic)
)
topics_per_outlet_list
```

# topic modelling for organisation for specific month

```{r get topics per organisation per month}
monthly_org_topics <- function(tidy_tweets_in, org, past_month, nr_topics) {
  # word count for specified media organisation
  word_counts <- tidy_tweets_in %>%
    mutate(time_floor = floor_date(created_at, unit = "month")) %>%
    select(user, word, time_floor) %>%
    # filter to specified org
    filter(user == org) %>%
    # filter to specified month
    filter(time_floor == as.Date(past_month)) %>%
    count(user, word, sort = TRUE) %>%
    ungroup()
  
  if (length(word_counts$user) == 0) {
    print(paste(org, "did not tweet the month starting on", past_month))
    return()
  }
    
  # create document term matrix
  # (treating all tweets from one organisation as one document)
  orgs_dtm <- word_counts %>%
    cast_dtm(user, word, n)

  # apply topic modelling
  orgs_lda <- LDA(orgs_dtm, k = nr_topics, control = list(seed = 1234))

  topics <- tidy(orgs_lda, matrix = "beta")
  return(topics)
}
```

```{r plot topics per organisation per month}
# org being the name of the media agency as found in the tidy_tweets dataframe
# past_month being the full date of the first day of that month - eg "2021-06-01" for June
model_topics_of_org_for_month <- function(tidy_tweets_in, org, past_month, nr_topics) {
  
  # topics for org for month
  orgs_topics <- monthly_org_topics(tidy_tweets_in, org, past_month, nr_topics)
  if (is.null(orgs_topics)) {
    return()
  }
  
  # find top words per topic
  top_terms <- orgs_topics %>%
    group_by(topic) %>%
    slice_max(beta, n = 5) %>% 
    ungroup() %>%
    arrange(topic, -beta)

  # plot top terms per topic
  top_terms %>%
    mutate(term = reorder_within(term, beta, topic)) %>%
    ggplot(aes(beta, term, fill = factor(topic))) +
    geom_col(show.legend = FALSE) +
    labs(title = paste("Topics for ", org, " for month starting ", past_month)) +
    facet_wrap(~ topic, scales = "free") +
    scale_y_reordered()
}
```

```{r}
# top words per topic (for sentiment analysis)
n_topics <- 3
words_per_topic <- 200
DailyMav_June_topics <- top_words_per_topic(monthly_org_topics(tidy_tweets, "DailyMaverick", "2021-06-01", 3), words_per_topic)

# plot
# Topics per media agency in June
# TODO: are we only doing June?
model_topics_of_org_for_month(tidy_tweets, "DailyMaverick", "2021-06-01", 3)
model_topics_of_org_for_month(tidy_tweets, "SABC", "2021-06-01", 3)
model_topics_of_org_for_month(tidy_tweets, "CapeTalk", "2021-06-01", 3)
model_topics_of_org_for_month(tidy_tweets, "EWN", "2021-06-01", 3)
model_topics_of_org_for_month(tidy_tweets, "News24", "2021-06-01", 3)
```

```{r Gina added: create list with topics per media outlet per month}
# TODO: are we only doing June?
JUNE1 <- "2021-06-01"

# TODO: Should indicate date on dataframe such that we know which month is associated with which dataframe in topics_per_outlet_month_list
# TODO: optimise this in some way with a loop?
topics_per_outlet_month_list <- list(
  top_words_per_topic(monthly_org_topics(tidy_tweets, "DailyMaverick", JUNE1, NUM_TOPICS_OUTLET), words_per_topic),
  top_words_per_topic(monthly_org_topics(tidy_tweets, "SABC", JUNE1, NUM_TOPICS_OUTLET), words_per_topic),
  top_words_per_topic(monthly_org_topics(tidy_tweets, "CapeTalk", JUNE1, NUM_TOPICS_OUTLET), words_per_topic),
  top_words_per_topic(monthly_org_topics(tidy_tweets, "EWN", JUNE1, NUM_TOPICS_OUTLET), words_per_topic),
  top_words_per_topic(monthly_org_topics(tidy_tweets, "News24", JUNE1, NUM_TOPICS_OUTLET), words_per_topic)
)
topics_per_outlet_month_list
```


<!----------------------------------------------------------------------------------------------------------------------------------------------------->
<!-- Topic Modelling for OUTSIDE SA Media Agencies -->
<!----------------------------------------------------------------------------------------------------------------------------------------------------->

```{r read external data}
# USA
cnn_tweets <- read.csv("data/cnnbrk_tweets.csv")
foxnews_tweets <- read.csv("data/FoxNews_tweets.csv")
# UK
bbcbreaking_tweets <- read.csv("data/BBCbreaking_tweets.csv")
# Global
time_tweets <- read.csv("data/time_tweets.csv")
economist_tweets <- read.csv("data/economist_tweets.csv")
bbcworld_tweets <- read.csv("data/bbcworld_tweets.csv")
AP_tweets <- read.csv("data/AP_tweets.csv")
firefox_tweets <- read.csv("data/firefox_tweets.csv")
```

```{r get relevant tweets for external data}
relevant_cnn <- filter_relevant_tweets(cnn_tweets)
relevant_foxnews <- filter_relevant_tweets(foxnews_tweets)
relevant_bbcbreaking <- filter_relevant_tweets(bbcbreaking_tweets)
relevant_time <- filter_relevant_tweets(time_tweets)
relevant_economist <- filter_relevant_tweets(economist_tweets)
relevant_bbcworld <- filter_relevant_tweets(bbcworld_tweets)
relevant_AP <- filter_relevant_tweets(AP_tweets)
relevant_firefox <- filter_relevant_tweets(firefox_tweets)
```

```{r combine all tweets into one dataframe for external data}
# combine all tweets into one dataframe
tweets <- bind_rows(relevant_cnn %>% mutate(user = "CNN"),
                    relevant_foxnews %>% mutate(user = "FoxNews"),
                    relevant_bbcbreaking %>% mutate(user = "BBCbreaking"),
                    relevant_time %>% mutate(user = "Time"),
                    relevant_economist %>% mutate(user = "Economist"),
                    relevant_bbcworld %>% mutate(user = "BBCworld"),
                    relevant_AP %>% mutate(user = "AP"),
                    relevant_firefox %>% mutate(user = "Firefox"))
```

```{r clean external data}
tidy_tweets <- clean_tweets(tweets)
```

# Topic Modeling overall

```{r}
model_topics_overall(tidy_tweets, 4)
```
# topic modelling over time

```{r}
model_topics_of_month(tidy_tweets, "2021-06-01", 4)
model_topics_of_month(tidy_tweets, "2021-05-01", 4)
model_topics_of_month(tidy_tweets, "2021-04-01", 4)
```
# topic modelling per organisation

```{r}
model_topics_of_org(tidy_tweets, "CNN", 3)
model_topics_of_org(tidy_tweets, "FoxNews", 3)
model_topics_of_org(tidy_tweets, "BBCbreaking", 3)
model_topics_of_org(tidy_tweets, "Time", 3)
model_topics_of_org(tidy_tweets, "Economist", 3)
model_topics_of_org(tidy_tweets, "BBCworld", 3)
model_topics_of_org(tidy_tweets, "AP", 3)
model_topics_of_org(tidy_tweets, "Firefox", 3)
```

# topic modelling for organisation for specific month

```{r}
# Topics per media agency for June
model_topics_of_org_for_month(tidy_tweets, "CNN", "2021-06-01", 3)
model_topics_of_org_for_month(tidy_tweets, "FoxNews", "2021-06-01", 3)
model_topics_of_org_for_month(tidy_tweets, "BBCbreaking", "2021-06-01", 3)
model_topics_of_org_for_month(tidy_tweets, "Time", "2021-06-01", 3)
model_topics_of_org_for_month(tidy_tweets, "Economist", "2021-06-01", 3)
model_topics_of_org_for_month(tidy_tweets, "BBCworld", "2021-06-01", 3)
model_topics_of_org_for_month(tidy_tweets, "AP", "2021-06-01", 3)
model_topics_of_org_for_month(tidy_tweets, "Firefox", "2021-06-01", 3)
```


```{r}
# Topics per media agency for May
model_topics_of_org_for_month(tidy_tweets, "CNN", "2021-05-01", 3)
model_topics_of_org_for_month(tidy_tweets, "FoxNews", "2021-05-01", 3)
model_topics_of_org_for_month(tidy_tweets, "BBCbreaking", "2021-05-01", 3)
model_topics_of_org_for_month(tidy_tweets, "Time", "2021-05-01", 3)
model_topics_of_org_for_month(tidy_tweets, "Economist", "2021-05-01", 3)
model_topics_of_org_for_month(tidy_tweets, "BBCworld", "2021-05-01", 3)
model_topics_of_org_for_month(tidy_tweets, "AP", "2021-05-01", 3)
model_topics_of_org_for_month(tidy_tweets, "Firefox", "2021-05-01", 3)
```


<!----------------------------------------------------------------------------------------------------------------------------------------------------->
<!-- Data Wrangling: Sentiment per topic -->
<!----------------------------------------------------------------------------------------------------------------------------------------------------->

# Sentiment per topic

```{r split topics into list of dataframes}
# split overall topics into a list with each dataframe only containing one topic and the term associated with it
term_per_topic_list <- topics_overall %>% 
  select(topic,term) %>% 
  group_split(topic)
term_per_topic_list
```

```{r apply vader sentiment analysis to list of topics on covid tweets}
# https://towardsdatascience.com/sentimental-analysis-using-vader-a3415fef7664
# all values greater than zeroes will be considered a positive review and all values less than zero would be considered as a negative review.
apply_vader <- function(df) {
  return(vader_df(df$term))
}

get_sentiment_mean <- function(df) {
  return(mean(df$compound))
}
```

```{r get topic sentiment mean per topic}
# TODO need to plot nicely (as table?)

# set names of topics
TOPIC <- list(paste0(1:length(term_per_topic_list)))
# TOPIC <- TOPIC %>% paste0(sep="")

# get average sentiment
vader_analysis_per_topic <- lapply(term_per_topic_list, apply_vader)
sentiment_mean_per_topic <- unlist(lapply(vader_analysis_per_topic, get_sentiment_mean))

# get sentiment mean per topic
overall_sentiment_per_topic <- data.frame(TOPIC, sentiment_mean_per_topic)
colnames(overall_sentiment_per_topic)[1] = "topic"
overall_sentiment_per_topic
```

```{r get topic sentiment mean per month}
# TODO need to plot nicely (as table?)

# set months to plot
MONTHS_TO_PLOT <- c("April", "May", "June")

# get average sentiment
vader_analysis_per_month <- lapply(topics_per_month_list, apply_vader)
sentiment_mean_per_month <- unlist(lapply(vader_analysis_per_month, get_sentiment_mean))

# get sentiment mean per per month
overall_sentiment_per_month <- data.frame(month=MONTHS_TO_PLOT, sentiment_mean_per_month)
overall_sentiment_per_month
```
```{r set outlet names to plot}
# set outlet names to plot
OUTLETS_TO_PLOT <- c("DailyMaveric", "SABC", "CapeTalk", "EWN", "News24")
```


```{r get topic sentiment mean per media outlet}
# TODO need to plot nicely (as table?)

# get average sentiment
vader_analysis_per_outlet <- lapply(topics_per_outlet_list, apply_vader)
sentiment_mean_per_outlet <- unlist(lapply(vader_analysis_per_outlet, get_sentiment_mean))

# get sentiment mean per per month
overall_sentiment_per_outlet <- data.frame(media_outlet=OUTLETS_TO_PLOT, sentiment_mean_per_outlet)
overall_sentiment_per_outlet
```
```{r get topic sentiment mean per media outlet per month}
# TODO need to plot nicely (as table?)

# get average sentiment
vader_analysis_per_outlet_month <- lapply(topics_per_outlet_month_list, apply_vader)
sentiment_mean_per_outlet_month <- unlist(lapply(vader_analysis_per_outlet_month, get_sentiment_mean))

# get sentiment mean per per month
overall_sentiment_per_outlet_month <- data.frame(media_outlet=OUTLETS_TO_PLOT, sentiment_mean_per_outlet_month)
overall_sentiment_per_outlet_month
```

<!----------------------------------------------------------------------------------------------------------------------------------------------------->
<!-- Data Visualisation: Sentiment per topic -->
<!----------------------------------------------------------------------------------------------------------------------------------------------------->

```{r plot overall sentiment per topic on covid-19}
ggplot(overall_sentiment_per_topic, aes(topic, sentiment_mean_per_topic, fill=topic)) +
  geom_col() +
  labs(title = "Overall sentiment per topic on covid-19",
       x="Topic",
       y="Vader Sentiment Score") +
  scale_fill_manual(values = c(dailymav_colour, ewn_colour, news24_colour, sabc_colour)) +
  custom_column_basic_theme()
```
```{r plot overall sentiment per month on covid-19}
ggplot(overall_sentiment_per_month, aes(month, sentiment_mean_per_month, fill=month)) +
  geom_col() +
  labs(title = "Overall sentiment per month on covid-19",
       x=NULL,
       y="Vader Sentiment Score") +
  scale_fill_manual(values = c(dailymav_colour, ewn_colour, news24_colour)) +
  custom_column_basic_theme()
```

```{r plot overall sentiment per outlet on covid-19}
ggplot(overall_sentiment_per_outlet, aes(media_outlet, sentiment_mean_per_outlet, fill=media_outlet)) +
  geom_col() +
  labs(title = "Overall sentiment per media outlet on covid-19",
       x=NULL,
       y="Vader Sentiment Score") +
  scale_fill_manual(values = c(dailymav_colour, ewn_colour, capetalk_colour, news24_colour, sabc_colour)) +
  custom_column_basic_theme()
```