---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(lubridate)
```

```{r Data: deaths}
data <- read.csv("data/covid19za_provincial_cumulative_timeline_deaths.csv")
head(data)
```
```{r tidying}
deaths <- data %>% pivot_longer(c('EC', 'FS', 'GP', 'KZN', 'LP', 'MP', 'NC', 'NW', 'WC', 'UNKNOWN'), names_to = "province", values_to = "deaths")
deaths <- deaths %>% 
  select(date, province, deaths, total)  %>% 
  filter(province != 'UNKNOWN') %>% 
  mutate(date = dmy(date))

head(deaths)
```
```{r total and daily deaths}
deaths_summary <- data %>%
  mutate(date = dmy(date)) %>%
  mutate(daily_deaths=total-lag(total,default=0)) %>%
  mutate(total_deaths = total) %>%
  select(date, daily_deaths, total_deaths)
```

```{r plot daily deaths}
ggplot(deaths_summary, aes(date, daily_deaths)) + 
  geom_col() +
  labs(title= "Daily deaths",
       caption = "Updated: June 2021",
       x = NULL,
       y = NULL) +
  theme_minimal()
```
```{r}
cases <- read.csv("data/covid19za_provincial_cumulative_timeline_confirmed.csv")
cases <- cases %>%
  mutate(date = dmy(date)) %>%
  mutate(total_confirmed_cases = total) %>%
  select(date, total_confirmed_cases)
head(cases)

```
```{r}
deaths_summary <- deaths_summary %>%
  left_join(cases, by="date") %>%
  mutate(fatality_rate = 100*(total_deaths / total_confirmed_cases))

head(deaths_summary)

```

```{r plot total deaths}
p1 <- ggplot() + 
  geom_point(data=deaths_summary, aes(date, total_deaths), color="blue") +
  labs(title= "Total Deaths",
       caption = "Updated: June 2021",
       x = NULL,
       y = NULL) +
  theme_minimal() +  
  theme(panel.grid.minor = element_blank(), 
  panel.grid.major = element_blank())

p1
```
```{r}
p2 <- ggplot(data=deaths_summary, aes(date, fatality_rate)) + 
  geom_point() +
  labs(title= "Case fatality rate",
       caption = "Updated: June 2021",
       x = NULL,
       y = NULL) +
  scale_y_continuous(breaks = seq(0, 10, by = 1), limits = c(0, 10), labels = function(x) paste0(x, '%')) +
  theme_minimal() +  
  theme(panel.grid.minor = element_blank(), 
  panel.grid.major = element_blank())

p2
```
```{r}
# adapted from https://drawar.github.io/posts/dual-y-axis-ggplot2/

# Get the plot grobs
g1 <- ggplotGrob(p1)
g2 <- ggplotGrob(p2)

# Get the locations of the plot panels in g1.
pp <- c(subset(g1$layout, name == "panel", se = t:r))

library(gtable)
library(grid)
# Overlap panel for second plot on that of the first plot
g1 <- gtable_add_grob(g1, g2$grobs[[which(g2$layout$name == "panel")]], pp$t, pp$l, pp$b, pp$l)

# ggplot contains many labels that are themselves complex grob; 
# usually a text grob surrounded by margins.
# When moving the grobs from, say, the left to the right of a plot,
# make sure the margins and the justifications are swapped around.
# The function below does the swapping.
# Taken from the cowplot package:
# https://github.com/wilkelab/cowplot/blob/master/R/switch_axis.R 
hinvert_title_grob <- function(grob){

# Swap the widths
widths <- grob$widths
grob$widths[1] <- widths[3]
grob$widths[3] <- widths[1]
grob$vp[[1]]$layout$widths[1] <- widths[3]
grob$vp[[1]]$layout$widths[3] <- widths[1]

# Fix the justification
grob$children[[1]]$hjust <- 1 - grob$children[[1]]$hjust 
grob$children[[1]]$vjust <- 1 - grob$children[[1]]$vjust 
grob$children[[1]]$x <- unit(1, "npc") - grob$children[[1]]$x
grob
}

# Get the y axis from g2 (axis line, tick marks, and tick mark labels)
index <- which(g2$layout$name == "axis-l")  # Which grob
yaxis <- g2$grobs[[index]]                  # Extract the grob

# yaxis is a complex of grobs containing the axis line, the tick marks, and the tick mark labels.
# The relevant grobs are contained in axis$children:
#   axis$children[[1]] contains the axis line;
#   axis$children[[2]] contains the tick marks and tick mark labels.

# Second, swap tick marks and tick mark labels
ticks <- yaxis$children[[2]]
ticks$widths <- rev(ticks$widths)
ticks$grobs <- rev(ticks$grobs)

# Third, move the tick marks
# Tick mark lengths can change. 
# A function to get the original tick mark length
# Taken from the cowplot package:
# https://github.com/wilkelab/cowplot/blob/master/R/switch_axis.R 
plot_theme <- function(p) {
plyr::defaults(p$theme, theme_get())
}

tml <- plot_theme(p1)$axis.ticks.length   # Tick mark length
#ticks$grobs[[1]]$x <- ticks$grobs[[1]]$x - unit(1, "npc") + tml

# Fourth, swap margins and fix justifications for the tick mark labels
ticks$grobs[[2]] <- hinvert_title_grob(ticks$grobs[[2]])

# Fifth, put ticks back into yaxis
yaxis$children[[2]] <- ticks

# Put the transformed yaxis on the right side of g1
g1 <- gtable_add_cols(g1, g2$widths[g2$layout[index, ]$l], pp$r)
g1 <- gtable_add_grob(g1, yaxis, pp$t, pp$r + 1, pp$b, pp$r + 1, clip = "off", name = "axis-r")

# Labels grob
left = textGrob("Total deaths", x = 0, y = 0.9, just = c("left", "top"), gp = gpar(fontsize = 14, col =  "blue"))
right =  textGrob("Fatality rate", x = 1, y = 0.9, just = c("right", "top"), gp = gpar(fontsize = 14))
labs = gTree("Labs", children = gList(left, right))

# New row in the gtable for labels
height = unit(3, "grobheight", left)
g1 <- gtable_add_rows(g1, height, 2)  

# Put the label in the new row
g1 = gtable_add_grob(g1, labs, t=3, l=3, r=5)

# Turn off clipping in the plot panel
g1$layout[which(g1$layout$name == "panel"), ]$clip = "off"

# Print to PDF
ggsave("deaths_and_fatality.pdf", g1, width=5, height=5)
```

```{r total deaths per province}
total_deaths <- tail(data, 1) %>% pivot_longer(c('EC', 'FS', 'GP', 'KZN', 'LP', 'MP', 'NC', 'NW', 'WC', 'UNKNOWN'), names_to = "province", values_to = "deaths")
total_deaths <- total_deaths %>% 
  select(date, province, deaths, total)  %>% 
  filter(province != 'UNKNOWN') %>% 
  mutate(date = dmy(date)) %>%
  arrange(desc(deaths))

total_deaths$province <- factor(total_deaths$province, levels = total_deaths$province)
total_deaths
```
```{r plot deaths by province}
ggplot(total_deaths, aes(province, deaths)) + 
  geom_col() +
  geom_text(aes(label = deaths), vjust = -1) +
  scale_x_discrete() +
  scale_y_continuous(labels = NULL) +
  labs(title= "Deaths by Province",
       caption = "Updated: June 2021",
       x = NULL,
       y = NULL) +
  theme_minimal()
```

