---
title: "Assignment 1: Gina Graphs"
output: html_notebook
---

# TODO: functions to create
- max in a column
- last element in column minus second last element in column

# Import libraries
```{r}
library(tidyverse)
library(lubridate)
library(formattable) # round numbers
```

# Read csv
```{r}
# general (cumulative) information regarding tests, deaths, and recoveries. Complete timeline.
tests_deaths_recoveries_data <- read.csv("data/covid19za_timeline_testing.csv")
head(tests_deaths_recoveries_data)

# total (cumulative) number of confirmed cases by province
provincial_total_confirmed <- read.csv("data/covid19za_provincial_cumulative_timeline_confirmed.csv")
head(provincial_total_confirmed)
```


# Deaths vs Recovered
```{r}
# total deaths
total_deaths <- max(tests_deaths_recoveries_data$deaths, na.rm = TRUE)
head(total_deaths)

# get last day's number of deaths increase
last_death_cols <- tail(tests_deaths_recoveries_data$deaths, n=2)
death_day_update <- last_death_cols[2] - last_death_cols[1]
head(death_day_update)

# total recovered
total_recovered <- max(tests_deaths_recoveries_data$recovered, na.rm = TRUE)
head(total_recovered)

# percentage recovered
percentage_recovered <- total_recovered / (total_recovered + total_deaths) * 100
head(formattable(percentage_recovered, digits = 1, format = "f")) # round to 1 digit
```
# Confirmed vs Active
```{r}
# total confirmed cases
total_confirmed <- max(provincial_total_confirmed$total, na.rm = TRUE)
head(total_confirmed)

# get last day's number of confirmed increase
last_confirmed_cols <- tail(provincial_total_confirmed$total, n=2)
confirmed_day_update <- last_confirmed_cols[2] - last_confirmed_cols[1]
head(confirmed_day_update)

# active cases = confirmed cases  - recoveries - deaths
total_active <- total_confirmed - total_recovered - total_deaths
head(total_active)
```

# Total number of tests and test day increase
```{r}
# get number of tests
total_tests <- max(tests_deaths_recoveries_data$cumulative_tests, na.rm = TRUE)
head(total_tests)
# get last day's number of tests increase
last_tests_cols <- tail(tests_deaths_recoveries_data$cumulative_tests, n=2)
test_day_update <- last_tests_cols[2] - last_tests_cols[1]
test_day_update
```


