---
title: "Confirmed and Active Cases by Province"
output: html_notebook
---
# TODO
* Add labels (total active and confirmed per province)
* Convert province codes to nice province names

# Import libraries
```{r}
library(tidyverse)
library(lubridate) # dates
library(formattable) # round numbers
library(ggplot2)
library(scales)
```

# Read csv
```{r}
# total (cumulative) number of confirmed cases by province
provincial_total_confirmed <- read.csv("data/covid19za_provincial_cumulative_timeline_confirmed.csv")
head(provincial_total_confirmed)

# provincial deaths, and recoveries
provincial_recoveries_data<- read.csv("data/covid19za_provincial_cumulative_timeline_recoveries.csv")
head(provincial_recoveries_data)
death_data <- read.csv("data/covid19za_provincial_cumulative_timeline_deaths.csv")
head(death_data)
```

# Confirmed vs Active cases per province

## Provincial confirmed
```{r}
provincial_confirmed <-  provincial_total_confirmed %>% pivot_longer(c('EC', 'FS', 'GP', 'KZN', 'LP', 'MP', 'NC', 'NW', 'WC', 'UNKNOWN'), names_to = "province", values_to = "confirmed")
provincial_confirmed <- provincial_confirmed %>%
  select(date, province, confirmed, total)  %>%
  filter(province != 'UNKNOWN') %>%
  mutate(date = dmy(date))

head(provincial_confirmed)
```


## Provincial recoveries
```{r}
provincial_recoveries <- provincial_recoveries_data %>% pivot_longer(c('EC', 'FS', 'GP', 'KZN', 'LP', 'MP', 'NC', 'NW', 'WC', 'UNKNOWN'), names_to = "province", values_to = "recoveries")
provincial_recoveries <- provincial_recoveries %>%
  group_by(province) %>%
  select(date, province, recoveries, total)  %>%
  filter(province != 'UNKNOWN') %>%
  mutate(date = dmy(date)) %>% 
  summarise(date = date, recoveries = recoveries)

head(provincial_recoveries)
```

## Provincial deaths
```{r tidying}
provincial_deaths <- death_data %>% pivot_longer(c('EC', 'FS', 'GP', 'KZN', 'LP', 'MP', 'NC', 'NW', 'WC', 'UNKNOWN'), names_to = "province", values_to = "deaths")
provincial_deaths <- provincial_deaths %>%
  select(date, province, deaths, total)  %>%
  filter(province != 'UNKNOWN') %>%
  mutate(date = dmy(date))

head(provincial_deaths)
```
```{r}
death_summary <- death_data %>%
  select(date, total) %>%
  mutate(date = dmy(date)) %>%
  mutate(daily_deaths=total-lag(total,default=0))
names(death_summary)[names(death_summary) == 'total'] <- 'total_deaths'
head(death_summary)
```

## Provincial Active

```{r}
# inner_join() joins based on matching keys (we only want overlapping dates)
provincial_active <- provincial_confirmed %>% 
  inner_join(provincial_recoveries, by = c("province", "date")) %>% 
  inner_join(provincial_deaths, by = c("province", "date"))
head(provincial_active)
```


## Get active cases per province
```{r Get active cases per province}
provincial_active$active <- with(provincial_active, confirmed - recoveries - deaths)
provincial_active <- provincial_active %>%
  select(date, province, confirmed, recoveries, deaths, active )
head(provincial_active)
```

```{r Plot}
ggplot(provincial_active, aes(date)) + 
  geom_line(aes(y = confirmed, colour = "Confirmed Cases"), color = "red") + 
  geom_line(aes(y = active, colour = "Active Cases"), color = "blue") +
  scale_y_continuous(breaks = seq(0, 1000000, by = 1000000), limits = c(0, 5000000), labels = NULL) +
  scale_x_date(labels = NULL) +
  facet_wrap(~ province, nrow = 2) +
  labs(title= "Confirmed and Active Cases by Province",
     caption = "Updated: June 2021",
     x = NULL,
     y = NULL) +
  theme_minimal()
```