---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(lubridate)
library(R.utils)
```
```{r Data: Vaccinations}
data <- read.csv("data/covid19za_timeline_vaccination.csv")
head(data)
```


```{r tidying}
vaccinations <- data %>%
  mutate(date = dmy(date)) %>%
  mutate(daily=vaccinations-lag(vaccinations,default=0)) %>%
  mutate(total = vaccinations) %>%
  select(date, daily, total)

head(vaccinations)
```

```{r Plot daily vaccinations}
ggplot(vaccinations, aes(date, daily)) + 
  geom_col() +
  labs(title= "Daily Vaccinations",
       caption = "Updated: June 2021",
       x = NULL,
       y = NULL) +
  theme_minimal()

```
```{r Plot total vaccinations}
ggplot(vaccinations, aes(date, total)) + 
  geom_smooth(color = "blue", se=F) + 
  geom_point(color = "blue") +
  scale_y_continuous(breaks = seq(0, 1000000, by = 500000), limits = c(0, 1000000)) +
  scale_x_date() + 
  labs(title= "Total Vaccinations",
       caption = "Updated: June 2021",
       x = NULL,
       y = NULL) +
  theme_minimal()
```

